# Generated by Django 4.2.20 on 2025-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_membership_notes_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
