# Generated by Django 4.2.20 on 2025-03-29 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_message_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
