# Generated by Django 5.1.6 on 2025-04-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_reply_disliked_by_reply_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='message',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='liked_by',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
