# Generated by Django 5.1.6 on 2025-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_update_event_datetime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If checked, non-members can access this event'),
        ),
    ]
