# Generated by Django 5.1.6 on 2025-03-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, non-members can access this event'),
        ),
    ]
