# Generated by Django 5.1.6 on 2025-03-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
    ]
