# Generated by Django 5.1.6 on 2025-03-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_attendance_checked_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='ticket_pdf',
        ),
    ]
