# Generated by Django 5.1.6 on 2025-04-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='value',
        ),
    ]
