# Generated by Django 5.1.6 on 2025-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_remove_benefit_icon_remove_benefit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='membership_group',
            field=models.CharField(choices=[('community', 'Community Member'), ('key_access', 'Key Access Member'), ('creative_workspace', 'Creative Workspace Member'), ('all', 'All Members')], default='all', help_text='The membership group that can access this benefit', max_length=20),
        ),
    ]
