# Generated by Django 5.1.6 on 2025-04-01 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_benefit_membership_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_benefit_usages', to=settings.AUTH_USER_MODEL)),
                ('user_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='benefits.userbenefit')),
            ],
            options={
                'verbose_name_plural': 'Benefit usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
