# Generated by Django 5.1.6 on 2025-04-01 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_benefitusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitusage',
            options={},
        ),
        migrations.RemoveField(
            model_name='benefitusage',
            name='notes',
        ),
        migrations.AddField(
            model_name='benefitusage',
            name='description',
            field=models.TextField(blank=True, help_text='Description of how the benefit was used', null=True),
        ),
        migrations.AlterField(
            model_name='benefitusage',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Admin or staff who recorded this usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_benefit_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benefitusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
