# Generated by Django 5.1.6 on 2025-04-01 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_alter_benefitusage_options_remove_benefitusage_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbenefit',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='userbenefit',
            name='usage_count',
        ),
        migrations.CreateModel(
            name='BenefitUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_benefits', to=settings.AUTH_USER_MODEL)),
                ('user_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='benefits.userbenefit')),
            ],
        ),
        migrations.DeleteModel(
            name='BenefitUsage',
        ),
    ]
