# Generated by Django 5.1.6 on 2025-03-31 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcontent',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='category',
            field=models.CharField(choices=[('Leadership', 'Leadership'), ('Marketing', 'Marketing'), ('Community', 'Community'), ('Events', 'Events'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontent',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='content_type',
            field=models.CharField(choices=[('course', 'Course'), ('template', 'Template'), ('webinar', 'Webinar'), ('article', 'Article'), ('video', 'Video'), ('ebook', 'E-Book'), ('podcast', 'Podcast'), ('other', 'Other')], default='course', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='content.digitalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Content Feedbacks',
                'unique_together': {('content', 'user')},
            },
        ),
    ]
