# Generated by Django 5.1.6 on 2025-03-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_digitalcontent_author_digitalcontent_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentFeedback',
        ),
    ]
