# Generated by Django 5.1.6 on 2025-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_contentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcontent',
            name='content_type',
            field=models.CharField(choices=[('course', 'Course'), ('template', 'Template'), ('webinar', 'Webinar')], default='course', max_length=20),
        ),
    ]
