# Generated by Django 5.1.6 on 2025-04-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_digitalcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcontent',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
